// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"DamageFix","status":false,"description":"Fixes battle damage/font popups being cut off at the top","parameters":{}}
];
